<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gv9rTyY' shared service.

return $this->privates['.service_locator.gv9rTyY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entitymanager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'user' => ['privates', '.errored..service_locator.gv9rTyY.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.gv9rTyY": it references class "App\\Entity\\User" but no such service exists.'],
]);
