<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWx0x0LQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWx0x0LQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWx0x0LQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWx0x0LQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWx0x0LQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Wx0x0LQ',
    'container.build_id' => '308ed250',
    'container.build_time' => 1549617353,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWx0x0LQ');
